version: '3'  
services: 
  tweetapp-docker-container:
    image: tweetapp-docker-compose:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/tweetapp-docker-container
    ports:
      - 8081:8081
    depends_on:
      - kafka
      - zookeeper 
  zookeeper:  
    image: wurstmeister/zookeeper  
    ports:  
      - 2181:2181  
  kafka:  
    image: wurstmeister/kafka  
    ports:  
      - 9092:9092
      - 9093:9093  
    links:
      - zookeeper
    environment: 
     KAFKA_ADVERTISED_HOST_NAME: kafka
     KAFKA_ADVERTISED_PORT: 9092
     KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
     KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
     KAFKA_LISTENERS: INSIDE://kafka:9093,OUTSIDE://0.0.0.0:9092
     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
     KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092 
    volumes:  
     - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper